---
--- Generated by Luanalysis
--- Created by 27164.
--- DateTime: 2024/4/20 9:15
---
-- 比较线程标识中与锁的标识是否一致
if(redis.call('get',KEYS[1]) == ARGV[1])
then
    return redis.call('del',KEYS[1])
end
return 0